import {
  AvailabilityType,
  Currency,
  DeliveryFormat,
  DeliveryMethod,
  PricingPer,
  RedemptionMethod,
} from "@octocloud/types";
import { LocaleDataProvider } from "../../../dataProviders/LocaleDataProvider";
import { TimeZoneDataProvider } from "../../../dataProviders/TimeZoneDataProvider";
import { ProductModel } from "../../../models/product/ProductModel";
import { OptionModel } from "../../../models/option/OptionModel";
import { UnitModel } from "../../../models/unit/UnitModel";
import { ProductContentModel } from "../../../models/product/ProductContentModel";
import { ProductPricingModel } from "../../../models/product/ProductPricingModel";

export class ProductTestDataProvider {
  public static product = {
    id: "id",
    internalName: "internalName",
    reference: null,
    locale: LocaleDataProvider.en,
    timeZone: TimeZoneDataProvider.europeLondon,
    allowFreesale: false,
    instantConfirmation: true,
    instantDelivery: true,
    availabilityRequired: true,
    availabilityType: AvailabilityType.START_TIME,
    deliveryFormats: [DeliveryFormat.PDF_URL, DeliveryFormat.QRCODE],
    deliveryMethods: [DeliveryMethod.TICKET, DeliveryMethod.VOUCHER],
    redemptionMethod: RedemptionMethod.DIGITAL,
    options: [
      {
        id: "id",
        default: true,
        internalName: "internalName",
        reference: null,
        availabilityLocalStartTimes: [],
        cancellationCutoff: "cancellationCutoff",
        cancellationCutoffAmount: 0,
        cancellationCutoffUnit: "cancellationCutoffUnit",
        requiredContactFields: [],
        restrictions: {
          minUnits: 0,
          maxUnits: null,
        },
        units: [],
      },
    ],
    title: "title",
    country: "country",
    location: "location",
    subtitle: "subtitle",
    shortDescription: "shortDescription",
    description: "description",
    highlights: [],
    inclusions: [],
    exclusions: [],
    bookingTerms: null,
    redemptionInstructions: null,
    cancellationPolicy: null,
    destination: {
      id: "id",
      default: true,
      name: "name",
      country: "country",
      contact: {
        website: null,
        email: null,
        telephone: null,
        address: null,
      },
      latitude: 0.0,
      longitude: 0.0,
    },
    categories: [],
    faqs: [],
    coverImageUrl: null,
    bannerImageUrl: null,
    videoUrl: null,
    galleryImages: [],
    bannerImages: [],
    defaultCurrency: Currency.EUR,
    availableCurrencies: [Currency.EUR],
    pricingPer: PricingPer.UNIT,
  };

  public static productModel = new ProductModel({
    id: this.product.id,
    internalName: this.product.internalName,
    reference: this.product.reference,
    locale: this.product.locale,
    timeZone: this.product.timeZone,
    allowFreesale: this.product.allowFreesale,
    instantConfirmation: this.product.instantConfirmation,
    instantDelivery: this.product.instantDelivery,
    availabilityRequired: this.product.availabilityRequired,
    availabilityType: this.product.availabilityType,
    deliveryFormats: this.product.deliveryFormats,
    deliveryMethods: this.product.deliveryMethods,
    redemptionMethod: this.product.redemptionMethod,
    optionModels: this.product.options.map(
      (option) =>
        new OptionModel({
          id: option.id,
          isDefault: option.default,
          internalName: option.internalName,
          reference: option.reference,
          availabilityLocalStartTimes: option.availabilityLocalStartTimes,
          cancellationCutoff: option.cancellationCutoff,
          cancellationCutoffAmount: option.cancellationCutoffAmount,
          cancellationCutoffUnit: option.cancellationCutoffUnit,
          requiredContactFields: option.requiredContactFields,
          restrictions: option.restrictions,
          unitModels: option.units.map((unit) => new UnitModel(unit)),
        })
    ),
    productContentModel: new ProductContentModel({
      title: this.product.title,
      country: this.product.country,
      location: this.product.location,
      subtitle: this.product.subtitle,
      shortDescription: this.product.shortDescription,
      description: this.product.description,
      highlights: this.product.highlights,
      inclusions: this.product.inclusions,
      exclusions: this.product.exclusions,
      bookingTerms: this.product.bookingTerms,
      redemptionInstructions: this.product.redemptionInstructions,
      cancellationPolicy: this.product.cancellationPolicy,
      destination: this.product.destination,
      categories: this.product.categories,
      faqs: this.product.faqs,
      coverImageUrl: this.product.coverImageUrl,
      bannerImageUrl: this.product.bannerImageUrl,
      videoUrl: this.product.videoUrl,
      galleryImages: this.product.galleryImages,
      bannerImages: this.product.bannerImages,
    }),
    productPricingModel: new ProductPricingModel({
      defaultCurrency: this.product.defaultCurrency,
      availableCurrencies: this.product.availableCurrencies,
      pricingPer: this.product.pricingPer,
    }),
  });
}
