name: Code Quality

on:
  push:
  pull_request:
    branches:
      - "**"
      - "!main"

jobs:
  coding-standard:
    name: "Coding Standards"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Setup node"
        uses: "actions/setup-node@v3"
        with:
          node-version: 16

      - name: "Install NPM dependencies"
        run: "npm ci"

      - name: "Run Prettier"
        run: "npm run format-check"

  static-code-analysis:
    name: "Static Code Analysis"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Setup node"
        uses: "actions/setup-node@v3"
        with:
          node-version: 16

      - name: "Install NPM dependencies"
        run: "npm ci"

      - name: "Run ESLint"
        run: "npm run lint"

  tests:
    name: "Tests"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Setup node"
        uses: "actions/setup-node@v3"
        with:
          node-version: 16

      - name: "Install NPM dependencies"
        run: "npm ci"

      - name: "Run Jest"
        run: "npm run test"
